<?php

if ($value->count() > 0) {
    ?>
        <table id="usertable" class="table table-bordered table-hover">
            <thead class="thead-light">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Zipcode</th>
                    <th>Product</th>
                    <th>Quantity</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="3">Total Order: <?php echo $value->count(); ?></td>
                </tr>
            </tfoot>
            <tbody>
                <?php foreach ($value as $u) { ?>
                    <tr>
                        <td><?php echo $u->order_id; ?></td>
                        <td><?php echo $u->customer_name; ?></td>
                        <td><?php echo $u->address; ?></td>
                        <td><?php echo $u->zipcode; ?></td>
                        <td><?php echo $u->product; ?></td>
                        <td><?php echo $u->quantity; ?></td>
                        <td><?php echo $this->tag->form("change/change"); ?>
                            <button name="change" value="<?php echo $u->customer_id; ?>">change</button>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    <?php
    }?>