<div class="mt-3" >
<?php echo $this->tag->linkTo(['addproduct/index', 'add products', 'class' => 'btn btn-primary']); ?>
<?php echo $this->tag->linkTo(['addproduct/add', 'see products', 'class' => 'btn btn-primary']); ?>
<?php echo $this->tag->linkTo(['addorder/see', 'see orders', 'class' => 'btn btn-primary']); ?>
<?php echo $this->tag->linkTo(['addorder/index', 'add orders', 'class' => 'btn btn-primary']); ?>
<?php echo $this->tag->linkTo(['setting/index', 'settings', 'class' => 'btn btn-primary']); ?>
</div>